# ai-agent-deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: kubeguardian/agent:latest   # Your AI agent Docker image
        imagePullPolicy: IfNotPresent

        ports: 
          - containerPort: 8081 
        env:
          - name: SESSION_DB_URL
            valueFrom:
              secretKeyRef:
                name: kubeguardian-secrets
                key: SESSION_DB_URL
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: kubeguardian-secrets
                key: GEMINI_API_KEY
          - name: AUTHORIZED_DIRECTORY
            value: /app/apps/bank-of-anthos/kubernetes-manifests
          - name: AUTHORIZED_NAMESPACE
            value: bank-of-anthos 
          - name: MCP_SERVER
            valueFrom:
              secretKeyRef:
                name: kubeguardian-secrets
                key: MCP_SERVER


--- 

# ai-agent-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: agent
spec:
  selector:
    app: agent
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
