# ai-agent-deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: kubeguardian/agent:latest   # Your AI agent Docker image
        imagePullPolicy: IfNotPresent

        ports: 
          - containerPort: 8081 
        env:
          - name: DB_URL
            value: postgresql://admin:admin123@accounts-db:5432/kubeguardian
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: gemini-secret
                key: GEMINI_API_KEY
