# ai-agent-deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-server
        image:  muhammadolammi/kubeguardian-mcp-server
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        ports: 
          - containerPort: 8086
        env:
          - name: AUTHORIZED_DIRECTORY
            value: /app/apps/bank-of-anthos/kubernetes-manifests
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: kubeguardian-secrets
                key: DB_URL
          - name: CRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: kubeguardian-secrets
                key: CRYPT_KEY


--- 

# ai-agent-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
