
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: frontend-cert
spec:
  domains:
    - kubeguardian.qtechconsults.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "kubeguardian"
    networking.gke.io/managed-certificates: "frontend-cert"
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: "gce"
  rules:
    - host: kubeguardian.qtechconsults.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agent
                port:
                  number: 80
    