# chat-deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: publsiher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publsiher
  template:
    metadata:
      labels:
        app: publsiher
    spec:
      containers:
      - name: publsiher
        image: kubeguardian/chat:latest   # Replace with your built Docker image
        imagePullPolicy: IfNotPresent

        ports: 
          - containerPort: 8082
        env:
          - name: RABBITMQ_URL
            value: amqp://guest:guest@rabbitmq:5672/
          