# chat-deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: kubeguardian/subscriber:latest   # Replace with your built Docker image
        imagePullPolicy: IfNotPresent

        ports: 
          - containerPort: 8083
        env:
          - name: RABBITMQ_URL
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: RABBITMQ_URL
          - name: SESSION_DB_URL
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: SESSION_DB_URL
          - name: AI_AGENT_URL
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: AI_AGENT_URL  
          - name: AUTHORIZED_NAMESPACE
            value: bank-of-anthos