# chat-deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image:  muhammadolammi/kubeguardian-sub
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

        ports: 
          - containerPort: 8083
        env:
          - name: CRYPT_KEY
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: CRYPT_KEY
          - name: DB_URL
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: DB_URL
          - name: RABBITMQ_URL
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: RABBITMQ_URL
          - name: SESSION_DB_URL
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: SESSION_DB_URL
          
          - name: AI_AGENT_URL
            valueFrom: 
              secretKeyRef:
                name: kubeguardian-secrets
                key: AI_AGENT_URL  
          - name: AUTHORIZED_NAMESPACE
            value: bank-of-anthos