apiVersion: apps/v1
kind: Deployment
metadata:
  name: faultyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faultyapp
  template:
    metadata:
      labels:
        app: faultyapp
    spec:
      containers:
        - name: faultyapp
          image: faulty_app:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"